baseURL: "http://davidlday.com/"
languageCode: "en-us"
title: "David L. Day"
theme: hugo-profile

Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

# markup:
#   goldmark:
#     renderer:
#       unsafe: true

Menus:
  main:
    - identifier: Me
      name: Me
      title: Me, in a nutshell.
      url: /#about
      weight: 1

    - identifier: books
      name: Books
      title: Some books I've published.
      url: /#books
      weight: 2

    - identifier: shorts
      name: Shorts
      title: Some short stories I've published.
      url: /#shorts
      weight: 3

    - identifier: experience
      name: Experience
      title: A shortened version of my resume.
      url: /#experience
      weight: 4

    - identifier: education
      name: Education
      title: Schools I attended.
      url: /#education
      weight: 5

    - identifier: contact
      name: Contact
      title: Contact me, for whatever reason.
      url: /#contact
      weight: 98

    # Dropdown menu
    - identifier: main
      title: Other Stuff
      name: Other Stuff
      weight: 99
    - identifier: posts-archive
      title: Old Blog Posts
      name: Posts Archive
      url: /posts-archive
      parent: main
      weight: 1
    - identifier: bibliography
      title: Bibliography
      name: Bibliography
      url: /bibliography
      parent: main
      weight: 2
    - identifier: writers-bio
      title: My Writer's Bio
      name: Writer's Bio
      url: /about
      parent: main
      weight: 3

params:
  title: "David L. Day"
  description: I don't live there anymore.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/avatar.jpg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

    # font:
    #   fontSize: 1.5rem # default: 1rem
    #   fontWeight: 500 # default: 400
    #   lineHeight: 1 # default: 1.5
    #   textAlign: right # default: left

    # color preference
    # color:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    #   primaryColor:
    #   secondaryColor:

    #   darkmode:
    #     textColor:
    #     secondaryTextColor:
    #     backgroundColor:
    #     secondaryBackgroundColor:
    #     primaryColor:
    #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    # align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # brandName: "Profile" # Brand name for the brand | default is the title variable
    # Completely customize the menu
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "👋, my name is"
    title: "David."
    subtitle: "Writer. Coder. Thinker."
    content: |-
      ...perhaps an over thinker. Scroll 👇 to learn more about me.
    image: /images/feature/one_day.jpg
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/davidlday/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/dday376/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/david-l-day.jpg"
    content: |-
      I love making things, playing video games, and spending time in the
      playground 🛝 of my own mind. 🧠

      I love my partner 👩 and children 🧒🧒.

      I love when ideas 💡 flow freely between people 🧑🏽‍🤝‍🧑🏽.

      I love books 📚.

      I've come to hate social media 🤡🤡 🗑️🔥.

      There's a bunch of facts about me below, if you're interested.

    skills:
      enable: false
      title: "Here are my top 5 strengths:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"

  # Experience
  experience:
    enable: true
    title: "Experience"
    items:
      - job: "Senior Principal"
        company: "Invesco"
        companyUrl: "https://careers.invesco.com/"
        date: "July 2022 - present"
        content:
          I am a Senior Principal of Data Systems at
          [Invesco](https://invesco.com). I'm part of the Enterprise Data
          Office, and help develop solutions around managing data products.

      - job: "Architect & Software Engineer"
        company: "Nationwide Insurance"
        companyUrl: "https://www.nationwide.com"
        date: "May 2000 - May 2022"
        featuredLink:
          enable: true
          name: My LinkedIn Profile
          url: "https://linkedin.com/in/dday376"
        content: |
          I spent much of my corporate career at Nationwide in Columbus, OH. Overall, it was a good company to work for, and gave me ample opportunity to work with a diverse range of people. Too many things to sum up here, so see my [LinkedIn Profile](https://linkedin.com/in/dday376) for details. Here's a listing of positions I held over the years:

            - Senior Technical Consultant in IT Applications
            - Consultant, IT Architecture in Infrastructure & Operations
            - Consulting IT Architect in Corporate Finance
            - Consultant, IT Application Development in Corporate Finance
            - Lead, Data Engineering in Corporate Finance
            - Lead, System Analyst in Corporate Finance

      - job: "Partner"
        company: "Cracked Skull Press"
        companyUrl: "https://crackedskullpress.com"
        date: "October 2021 - present"
        info:
          enable: false
        featuredLink:
          enable: true
          name: That Which Cannot Be Undone
          url: "https://crackedskullpress.com/books/twcbu/"
        content: |
          I'm currently a partner in Cracked Skull Press, an independent publishing company in Columbus, OH, founded in 2021. Our initial project, That Which Cannot Be Undone, is an anthology of horror stories by Ohio authors, all set in Ohio.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Master of Arts, Writing Popular Fiction"
        school:
          name: "Seton Hill University"
          url: "https://www.setonhill.edu/"
        date: "2009 - 2011"
        # GPA: "3.9 out of 5.0"
        # content:
        featuredLink:
          enable: true
          name: "My Thesis Novel, Tearstone"
          url: "https://darkrecessespress.com/product/tearstone-2/"
      - title: "Master of Business Administration"
        school:
          name: "Ohio University"
          url: "https://www.ohio.edu/"
        date: "1994 - 1995"
        # GPA: "3.8 out of 5.0"
        # content:
      - title: "Bachelor of Arts, English"
        school:
          name: "Ohio University"
          url: "https://www.ohio.edu/"
        date: "1990 - 1993"
        # GPA: "4.2 out of 5.0"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    title: "Short Stories"
    items:
      - title: The Infernal Gift
        content: That Which Cannot Be Undone, October 2022.
        url: https://www.crackedskullpress.com/books/twcbu/
      - title: Defend Atlantis
        content: Terror Politico, January 2019
        url: https://amzn.to/2sjK14h
      - title: Vacation
        content: Aurora Wolf, Vol. 9 Issue 10, October 2018
        url: https://aurorawolf.com/2018/10/vacation/
      - title: Black Hand
        content: Double Feature Magazine, Issue 1, October 2016
        url: http://amzn.to/2dwD20r
      - title: A Gathering of Lost Shadows
        content: Hazard Yet Forward, August 2012
        url: http://amzn.to/1Lj59rf
      - title: Gray
        content: Necrotic Tissue, Issue 5, January 2009

  # Achievements
  shorts:
    enable: true
    title: "Short Stories"
    items:
      - title: The Infernal Gift
        content: That Which Cannot Be Undone, October 2022.
        url: https://www.crackedskullpress.com/books/twcbu/
      - title: Defend Atlantis
        content: Terror Politico, January 2019
        url: https://amzn.to/2sjK14h
      - title: Vacation
        content: Aurora Wolf, Vol. 9 Issue 10, October 2018
        url: https://aurorawolf.com/2018/10/vacation/
      - title: Black Hand
        content: Double Feature Magazine, Issue 1, October 2016
        url: http://amzn.to/2dwD20r
      - title: A Gathering of Lost Shadows
        content: Hazard Yet Forward, August 2012
        url: http://amzn.to/1Lj59rf
      - title: Gray
        content: Necrotic Tissue, Issue 5, January 2009

  books:
    enable: true
    title: "Books"
    items:
      - title: Miscalculations
        content: |-
          Currently Unavailable. A collection of poetry from my younger years. Some I'm proud of, others, not so much. I'm looking into options for re-releasing in a sustainable way.
        image: /images/covers/miscalculations.jpg
        # featured:
        #   name: Dark Recesses Press
        #   link: https://darkrecessespress.com/product/tearstone-2/
      - title: Tearstone
        content: |-
          "Tearstone is a pitch black work of horror that has it all: high action terror, bizarro nightmares, and soul-scarring occultism. Don't overlook this new occult thriller, and make sure you keep watching David Day. He's part of the new dawn of the horror genre, and its already rising." - Michael A. Arnzen, Bram Stoker Award-winning Author of Play Dead
        image: /images/covers/tearstone.jpg
        featured:
          name: Dark Recesses Press
          link: https://darkrecessespress.com/product/tearstone-2/

  # projects
  projects:
    enable: false
    title: "Project"
    items:
      - title: Miscalculations
        content: |-
          Currently Unavailable. A collection of poetry from my younger years. Some I'm proud of, others, not so much. I'm looking into options for re-releasing in a sustainable way.
        image: /images/covers/miscalculations.jpg
        # featured:
        #   name: Dark Recesses Press
        #   link: https://darkrecessespress.com/product/tearstone-2/
      - title: Tearstone
        content: |-
          "Tearstone is a pitch black work of horror that has it all: high action terror, bizarro nightmares, and soul-scarring occultism. Don't overlook this new occult thriller, and make sure you keep watching David Day. He's part of the new dawn of the horror genre, and its already rising." - Michael A. Arnzen, Bram Stoker Award-winning Author of Play Dead
        image: /images/covers/tearstone.jpg
        featured:
          name: Dark Recesses Press
          link: https://darkrecessespress.com/product/tearstone-2/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        # - icon: fab fa-twitter
        #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      # - title: Image Converter
      #   content:
      #     A web app to convert image to pdf, png to jpg, png to jpg and png to
      #     webp without database using django.
      #   image: /images/projects/converter.jpg
      #   featured:
      #     name: Demo
      #     link: https://django-converter.herokuapp.com
      #   # badges:
      #   #   - "Django"
      #   #   - "Bootstrap"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/converter

      # - title: Hugo Profile V2
      #   content:
      #     A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   # badges:
      #   #   - "Hugo"
      #   #   - "Bootstrap"
      #   #   - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content:
      My inbox is always open. Whether you have a question or just want to say
      hi, I’ll try my best to get back to you! I don't "social media" much
      anymore, but email still works fine.
    email: david@davidlday.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/davidlday
      linkedin: https://linkedin.com/in/dday376
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com
